### PR TITLE
Add strings to prerequisites for elons-toys. (#1598)

### LINKED ISSUE #1598: elons-toys: add missing prerequisite
The `elons-toys` exercise requires students to do string formatting, but does not have strings in [its prerequisites](https://github.com/exercism/go/blob/main/config.json#L174). The `strings` concept should be added to its prerequisites.

### PR DESCRIPTION
**Pull request by bobtfish**
Fixes #1598

### CODE REVIEW

**Comment by jmrunkle** [comment]
Sorry, gotta fix the broken CI first... See #1633

**Review by jmrunkle — APPROVED** [review]
Looks fine to me, but please pull in latest changes so that we can pass configlet lint and then I can merge this PR.

**Comment by ErikSchierboom** [comment]
@jmrunkle The linting error is unrelated to this PR.

**Comment by ErikSchierboom** [comment]
@iHiD Could you approve?

**Comment by jmrunkle** [comment]
> @jmrunkle The linting error is unrelated to this PR.

I am aware. Unfortunately the Configlet lint must be passing before it lets you merge. I already approved it.

**Comment by iHiD** [comment]
Should I merge?

**Comment by bobtfish** [comment]
I've just rebased, so hopefully it should pass lint now. Thanks @iHiD @jmrunkle <3

**Comment by ErikSchierboom** [comment]
Merged. Thanks @bobtfish!

**Pull request merged**
