### PR TITLE
Fix matrix test variable type

### PR DESCRIPTION
**Pull request by antklim**
In the matrix exercise, the function New is expected to return a tuple with the types `*Matrix, error`.
However, in the `BenchmarkNew` test, the matrix variable defined a variable of type `Matrix`. It causes compilation errors due to type mismatch. 

This PR proposes a test code fix. It is also related to other open PR #1431.

Thanks.

### CODE REVIEW

**Review by dittrichlucas — APPROVED** [review]

**Comment by ekingery** [comment]
Unfortunately I don't have time to dive into the original issue in #1431. I was going to approve this change, however I think we would need to also update the `.meta/example.go` file. Ideally someone could take a fresh look at this exercise and make a call on the issues discussed in #1431, make sure it conforms to the new V3 specs, etc.

**Comment by jmrunkle** [comment]
@antklim - can you pull in the changes from main and then rebase so that we can get a clean run of the CI tests? I want to see if this is actually passing. If it is, I am in favor of approving this so that students can actually choose between different solutions and discuss that in mentoring.

I could also be persuaded that we should actually get rid of benchmark tests completely from our test suites and simply allow students to do their own benchmarking if they would like to. Benchmarking is something that seems outside of the normal purview of exercism v3's MO.

**Comment by antklim** [comment]
@jmrunkle I just rebased from main and resolved conflicts.

**Comment by jmrunkle** [comment]
Yeah, it is what I was afraid of, this does not pass CI:

```
practice/matrix/matrix_test.go:277:17: cannot use New("1 2 3 10 11\n4 5 6 11 12\n7 8 9 12 13\n 8 7 6 13 14") (value of type Matrix) as *Matrix value in assignment (typecheck)
		matrix, err = New("1 2 3 10 11\n4 5 6 11 12\n7 8 9 12 13\n 8 7 6 13 14")
```

**Comment by jmrunkle** [comment]
So the stub actually make no assertion about what it returns and the exemplar returns (Matrix, error): https://github.com/exercism/go/blob/main/exercises/practice/matrix/.meta/example.go#L14

**Comment by antklim** [comment]
@jmrunkle I made changes in stub signature. I hope it will fix the build.

**Review by jmrunkle — APPROVED** [review]

**Pull request merged**
