### PR TITLE
Add stub files

### PR DESCRIPTION
**Pull request by leenipper**
Adds the missing stub files to address issue #1265 with updates to applicable README.md for two exercises.

### CODE REVIEW

**Comment by bitfield** [comment]
One thing which occurs to me is that Parallel Letter Frequency already has a kind of 'stub file' (`frequency.go`), and this is very often the cause of confusion. Students will take the FreqMap type and Frequency function defined there, copy it into their own solution file, and then (to avoid a duplicate definition error) delete the original `frequency.go`. Of course when they submit the solution and a mentor downloads it, the `frequency.go` is still present, meaning the solution doesn't compile. This breaks Exalysis, for example.

Should we make it clearer that students are intended to add their code to `frequency.go` somehow?

**Comment by bitfield** [comment]
That sounds fine; in which case, let's delete the `frequency.go` file from the repo and move the Frequency/FreqMap code into the stub file. They are not actually stubs as such, but the student's code is required to call them.

**Comment by bitfield** [comment]
In that case, should we add them to the example file as well? Or will that simply cause more duplicate declaration errors?

**Comment by leenipper** [comment]
That works. No duplicate declaration errors, since use of example.go is always without the stub file.
And it should solve the problem with students doing the wrong thing.

**Comment by leenipper** [comment]
I simplified the new section in the README.md files.  Sometimes saying less is better.

**Comment by leenipper** [comment]
@bitfield , take another look, time permitting.  Thanks.

**Comment by leenipper** [comment]
@bitfield , ok for merging ?

**Pull request merged**
