### PR TITLE
New concept exercise: panic/recover

### PR DESCRIPTION
**Pull request by myworkcircle**
Related: #1373

First iteration for Exercise Concept for Panic Recover

+ pani_recover.go
+ panic_recover_test.go

Upcoming iteration-
1. Add more methods to panic_recover.go
2. Add more test cases to panic_recover_test.go
3. Add .meta folder including config, exemplar, design files
4. Add .docs folder

### CODE REVIEW

**Comment by myworkcircle** [comment]
Not able to pass github tests for PR can you helpo please @junedev

**Comment by andrerfcsantos** [comment]
I can't see that error specifically, only [this one](https://github.com/exercism/go/runs/5710819350?check_suite_focus=true):

```console
Error: tmp/lint/concept/panic_recover/panic_recover_test.go:43:2: undeclared name: `fmt` (typecheck)
	fmt.Println(val)
	^
Error: tmp/lint/concept/panic_recover/panic_recover_test.go:41:3: val declared but not used (typecheck)
		val := CreatePanic(tt.name, len(tt.name))
		^
```

I think you tried to solve the "val declared but not used" with the print, but you are not importing `fmt` in the tests.

Just to give you a bit more context: the script we have in CI copies the `.meta/exemplar.go` to a folder with the tests you provide and runs the tests against the exemplar. So, for local development you probably want to keep editing `panic_recover.go` and implement the solution there, just so you have the tests in the same folder of the solution. When you want to run that solution here in CI copy your implemented solution from `panic_recover.go` to `.meta/exemplar.go` and push. When you feel you have the code for the exemplar completely ready and you won't do any more code changes, you can replace the code in `panic_recover.go` to have the stub and leave the solution in the exemplar.

**Comment by myworkcircle** [comment]
> I can't see that error specifically, only [this one](https://github.com/exercism/go/runs/5710819350?check_suite_focus=true):
> 
> ```
> Error: tmp/lint/concept/panic_recover/panic_recover_test.go:43:2: undeclared name: `fmt` (typecheck)
> 	fmt.Println(val)
> 	^
> Error: tmp/lint/concept/panic_recover/panic_recover_test.go:41:3: val declared but not used (typecheck)
> 		val := CreatePanic(tt.name, len(tt.name))
> 		^
> ```
> 
> I think you tried to solve the "val declared but not used" with the print, but you are not importing `fmt` in the tests.
> 
> Just to give you a bit more context: the script we have in CI copies the `.meta/exemplar.go` to a folder with the tests you provide and runs the tests against the exemplar. So, for local development you probably want to keep editing `panic_recover.go` and implement the solution there, just so you have the tests in the same folder of the solution. When you want to run that solution here in CI copy your implemented solution from `panic_recover.go` to `.meta/exemplar.go` and push. When you feel you have the code for the exemplar completely ready and you won't do any more code changes, you can replace the code in `panic_recover.go` to have the stub and leave the solution in the exemplar.
> 
> Also, instead of `go/exercises/concept/panic-recover` we tend to have simpler module/package names for the exercises. The module/package can just be called something like `panicrecover` in this case.

thanks @andrerfcsantos will update the code as you said

**Comment by andrerfcsantos** [comment]
@myworkcircle It has been a few days since the last update to this PR. Are you still working on this? Can we help with anything?

I'm just asking to know if you are no longer interested in working on this or if you just got busy, or if you are stuck with something. If you just got busy, there's no problem. There's no rush from our side, so don't let this comment pressure you - take your time to finish this. If you are no longer interested in this, that's fine too, just let us know.

**Comment by myworkcircle** [comment]
Hey Andre,

Sorry for delay in the task. Actually i had started the task then i got
stuck with writing the test cases. As to how to write test cases to check
for panic itself.

Recently i got occupied with some personal issues, so couldn't give time to
this task.

I would say that although im interested in the task. But seeing the current
turn of events i will not be able to again start this task for sometime,
due to some tight schedule for some launches. Really sorry for this.

I understand that task has gotten a lot delayed, So im perfectly fine if
you want to assign this task to someone else.

I can later see how the other person has implemented it and discuss on the
same if i have any doubts. Eventually i believe the goal is to learn and
help the community.


Thanks and Regards,
Pallav Agarwal

**Comment by andrerfcsantos** [comment]
@myworkcircle No problem, thanks for letting us know. We won't assign it to anyone for now, so feel free to come back at any time.

To test for panics, maybe you can take as inspiration the way the [testify.assert](https://pkg.go.dev/github.com/stretchr/testify/assert) package does it. They have several tests for testing for panics, and you can check their source code. For instance, something like this would be an easy way to check for a panic: [assertions.go](https://github.com/stretchr/testify/blob/083ff1c0449867d0d8d456483ee5fab8e0c0e1e6/assert/assertions.go#L1007)

**Review by junedev — COMMENTED** [review]
I browsed through the current state and wanted to leave some notes about general things I noticed. If you were already aware of those, then just do you thing and don't mind me. :wink: 

* Exercism's markdown rules say to use one line per sentence: https://exercism.org/docs/building/markdown/markdown#h-one-sentence-per-line (I added the general link to the issue description as well now)
* The exercise needs a small story/ a theme and the tasks should be phrased along that theme. Have a look at other concept exercises to get a better understanding of this. The important thing to note here is that the slug also needs to be derived from that story, not from the concept name. For example the concept `for-loops` is taught by the exercise `bird-watcher`. So the folders and files of the exercise also include `bird-watcher` and not `for-loops`. The same should apply to your exercise. The exercise needs a name that fits the story and then the one concept it teaches should be called `panic-recover`.
* Besides the exercise, you also need to create a new concept in the `concepts` folder called `panic-recover`. Don't worry, you don't need any new content for this but CI will not pass before this is added. See https://exercism.org/docs/building/tracks/concepts. You can put the same content you have in the exercise introduction.md also in the concept introduction.md and in the concept about.md. No need to make up something different at this point.
* Just as information: defer will later most likely be moved into its own concept and exercise but until then it is good that you explained it a bit in the introduction.

**Comment by junedev** [comment]
I am sorry but I will have to put this on hold for now.

Here the official note about this:

> We are currently in a phase of our journey where we have paused community contributions to allow us to take a breather and redesign our community model. You can learn more in [this blog post](https://exercism.org/blog/freeing-our-maintainers). **As such, all issues and PRs in this repository are being closed.**
> 
> That doesn't mean we're not interested in your ideas, or that if you're stuck on something we don't want to help. The best place to discuss things is with our community on the Exercism Community Forum. You can use [this link](https://forum.exercism.org/new-topic?title=${encodeURI(subject.title)}&body=${encodeURI(subject.body)}&category=${encodeURI(forumCategory)}) to copy this into a new topic there.

**Pull request closed without merging**
