### PR TITLE
Remove unused 'input' field

### PR DESCRIPTION
**Pull request by Caesarovich**
The input field is unused and causes a linter warning, which might be confusing for someone doing this exercise.

Screenshot from 2024-03-06 18-24-03

### CODE REVIEW

**Review by andrerfcsantos — APPROVED** [review]

**Review by andrerfcsantos — CHANGES_REQUESTED** [review]
Can you also make this change in the [gen.go](https://github.com/exercism/go/blob/main/exercises/practice/resistor-color/.meta/gen.go) file?

**Comment by Caesarovich** [comment]
Hi, thanks for replying.

I did not notice this .meta folder at first, my bad.
I am not quite sure to understand yet how it works, please let me know if my latest commit contains errors.

**Comment by Caesarovich** [comment]
Any follow up @andrerfcsantos ?

**Review by andrerfcsantos — APPROVED** [review]
Sorry for taking so long to review this. This looks good!

**Comment by andrerfcsantos** [comment]
Closing and reopening to force CI to run.

**Comment by andresantos-blip** [comment]
@Caesarovich I don't usually like to mess with other people branches, but in the interest of getting this merged, I merged main from the main repository into your branch. I did this to ensure your branch was up-to-date and to make sure it didn't conflict with anything else introduced in main meanwhile.

I also made an extra commit in the branch formatting the gen.go file.

**Comment by andrerfcsantos** [comment]
@Caesarovich I don't like to mess with other people's branches, but in the interest of merging this, I merged main from upstream into your branch. I also made an extra commit fixing a formatting warning in `gen.go`.

Thanks for this!

**Pull request merged**
