### PR TITLE
Changes to iterating map output.

### PR DESCRIPTION
**Pull request by rishabhvs**
Sequence seemed incorrect. Made appropriate changes.

### CODE REVIEW

**Comment by andrerfcsantos** [comment]
The Go language specification states that in a map, the iteration order is not guaranteed: [Go Language Spec: Range Clause](https://go.dev/ref/spec#RangeClause)

> 3. The iteration order over maps is not specified and is not guaranteed to be the same from one iteration to the next.

So, technically the order presented is possible.

Maybe we can change the instructions to add a quick note explicitly addressing this, to avoid someone to be confused about this like you were?

If you want to add that note, consider using one of the special blocks we allow in exercism. See the "Special Blocks" section in [Exercism Docs: Markdown Specification](https://exercism.org/docs/building/markdown/markdown). Also refer to the previous comment of the bot to see other places where you must also change this.

**Comment by andrerfcsantos** [comment]
@rishabhvs  Let us know if you are still interested in working on this. It's totally fine if you are not, we can finish this for you. If you are still interested in working on this feel free to take your time, there's no rush.

**Comment by rishabhvs** [comment]
@andrerfcsantos Added the note using special blocks.

**Comment by andrerfcsantos** [comment]
Thanks! Made some tweaks to make the explanation clearer and added the note to the concept and exercise introduction too.

**Pull request merged**
