### PR TITLE
poker: add a hints file

### LINKED ISSUE #853: poker: README needs more implementation detail
[It](https://github.com/exercism/go/blob/master/exercises/poker/README.md) is fairly sparse on the expected implementation.

### PR DESCRIPTION
**Pull request by shaleh**
Document what the input and output of `BestHand` should be.

Closes #853

### CODE REVIEW

**Comment by shaleh** [comment]
I know the README is supposed to be updated. Where is the tool that handles this?

**Comment by tleen** [comment]
It's [configlet](https://github.com/exercism/configlet): your swiss army knife of track configuration! The README there is behind a bit (exercism/configlet#91), but I provide [some instructions](https://github.com/exercism/go#exercism-go-style) in our README. Do those make sense?

**Comment by tleen** [comment]
A reminder to me that this is waiting on exercism/configlet#91.

**Comment by tleen** [comment]
@shaleh I updated the configlet README to contain info on how to generate READMEs.

**Comment by tleen** [comment]
I'm gonna go ahead and merge this, then it will be available next time the README is generated.

**Pull request merged**
