### PR TITLE
travis: bump go versions

### PR DESCRIPTION
**Pull request by HaraldNordgren**

### CODE REVIEW

**Comment by HaraldNordgren** [comment]
@hilary Ping

**Comment by ferhatelmas** [comment]
@HaraldNordgren thanks but could you scroll to the bottom file where you will see another place that needs updating ?

**Comment by HaraldNordgren** [comment]
@ferhatelmas Updated.

**Comment by ferhatelmas** [comment]
@HaraldNordgren great, thanks. There were some changes for gofmt in 1.11 so fmt task is failing, could you give a look to it, too ?

> please run 'go fmt' on exercises/scrabble-score/

**Comment by HaraldNordgren** [comment]
@ferhatelmas Updated.

**Pull request merged**
