### PR TITLE
regenerated test-cases

### PR DESCRIPTION
**Pull request by eklatzer**
Hey, I regenerated the test-cases because of the newly added test-cases in the problem specification 

Details:
* https://github.com/exercism/problem-specifications/pull/2056
* https://github.com/exercism/problem-specifications/issues/2054

### CODE REVIEW

**Review by andrerfcsantos — CHANGES_REQUESTED** [review]
Cool! Thanks for doing this.

Did you use the test generator to create the test cases? If so, it should have also changed [tests.toml](https://github.com/exercism/go/blob/main/exercises/practice/luhn/.meta/tests.toml) - changes to this file must also be committed, as it is the way [configlet](https://github.com/exercism/configlet) can detect if an exercise is sync with problem specs or not.

**Comment by eklatzer** [comment]
Hey, I used `GO111MODULE=off go run exercises/practice/luhn/.meta/gen.go` to generate it. I have used it again, but `tests.toml` hasn't changed. I have also tried deleting the local `problem-specifications` but using remotes ones also did not change anything.

**Comment by eklatzer** [comment]
When should myself to the `contributors` in `config.json`? Also when regenerating the test-cases?

**Comment by andrerfcsantos** [comment]
> Hey, I used GO111MODULE=off go run exercises/practice/luhn/.meta/gen.go to generate it. I have used it again, but tests.toml hasn't changed. I have also tried deleting the local problem-specifications but using the remote one also did not change anything. EDIT: I will regenerate everything using configlet

My bad, it is configlet that should generate that file indeed. I haven't run this workflow in a while and I was under the (wrong) impression that the tests generators that should generate this test case, but it not. It is indeed configlet. So if you use configlet to update the file metadata (the .toml) file and then run the test generator, the test generator should use the .toml file to create the tests. That should work.

> When should myself to the contributors in config.json? Also when regenerating the test-cases?

You can!

**Comment by eklatzer** [comment]
Hey, I know used the following commands:
```
configlet sync --tests include -u -e luhn
GO111MODULE=off go run exercises/practice/luhn/.meta/gen.go
```

This part should maybe be updated: https://github.com/exercism/go#generating-test-cases

**Comment by andrerfcsantos** [comment]
> This part should maybe be updated: https://github.com/exercism/go#generating-test-cases

@eklatzer Yes, we should update that part :)

**Pull request merged**
