### PR TITLE
Fix Go code formatting in codeblock (concepts/methods)

### PR DESCRIPTION
**Pull request by IsaacG**

### CODE REVIEW

**Review by junedev — COMMENTED** [review]
Would be great if you can apply the fix(es) to the about.md and the exercise introduction as well.

**Comment by IsaacG** [comment]
> Would be great if you can apply the fix(es) to the about.md and the exercise introduction as well.

This issue does not exist in those files. One does not have this code. The other has the "fixed" version.

**Comment by junedev** [comment]
? I can see the issue with the missing space here https://github.com/exercism/go/blob/main/concepts/methods/about.md for example

**Comment by IsaacG** [comment]
Sorry about that. I'm not sure why I couldn't see that. I did a `grep -rlF '){'` to pick up all occurrences this time.

**Review by junedev — APPROVED** [review]

**Pull request merged**
