### PR TITLE
Docs(concept-methods): update code block to have correct formatting

### PR DESCRIPTION
**Pull request by ynfle**
Validated with `go fmt`

### CODE REVIEW

**Comment by ynfle** [comment]
(I'd appreciate an hacktoberfest label if the change is significant enough)

**Review by junedev — APPROVED** [review]

**Comment by ynfle** [comment]
I can't merge it FYI

**Comment by junedev** [comment]
This PR is rather small but you have been very helpful on the issue side etc so I am fine applying the label here.

**Comment by ynfle** [comment]
Thanks! I will hopefully get it on other PRs so not a big deal. Thanks either way!

**Comment by junedev** [comment]
Re the merge: I was about to take of that but I noticed you did not update the exercise introduction. Did you check for the error there as well?

**Comment by ynfle** [comment]
> @ynfle Re the merge: I was about to take of that but I noticed you did not update the exercise introduction. Did you check for the error there as well?

@junedev yes, it is formatted correctly

**Pull request merged**
