### PR TITLE
elons-toys: refactor according to #1782

### LINKED ISSUE #1782: elons-toys: issues
- function aren't in order of tasks 
  - `CanFinish` comes before `DisplayDistance` while their tasks are flipped
- no task for `Create` functions for `Car` & `Track` structs

### PR DESCRIPTION
**Pull request by mcastorina**
Fixes #1782

### CODE REVIEW

**Comment by junedev** [comment]
Thanks for working on this. The tests run against the exemplar file in the .meta folder of the exercise. That one also needs to be updated.

**Comment by junedev** [comment]
@mcastorina This is ready to go, right?
It helps if you either request a re-review or leave a comment that you are done, so the maintainer knows it's their turn again. 🙂

**Comment by mcastorina** [comment]
Ah yes, sorry! Ready for re-review :)

**Comment by junedev** [comment]
I added the design file update that I forgot to mention.

I find it a bit hard to tell whether the exercise is smooth now or whether there are still issues. I will merge this and we will see whether someone still complains. 😉

**Pull request merged**
