### PR TITLE
Sync docs

### PR DESCRIPTION
**Pull request by IsaacG**
Sync exercise docs using `configlet sync -u -y --docs`. Revert documents which have diverged significantly from the problem specs.

### CODE REVIEW

**Comment by junedev** [comment]
@IsaacG This PR doesn't have a description but it looks like you were syncing all exercise descriptions. Did you check them one by one that the exercise still makes sense (instructions fit to tests etc)? 
André and I noticed a while back that some Go practice exercises were not in line with their problem spec equivalent, append files were not used in all places for changes, different test cases were used etc. Also some exercises in problem spec changed quite a bit (like grade school) so that only updating the docs would lead to an inconsistent state.

**Review by junedev — COMMENTED** [review]
@IsaacG This PR doesn't have a description but it looks like you were syncing all exercise descriptions. Did you check them one by one that the exercise still makes sense (instructions fit to tests etc)? 
André and I noticed a while back that some Go practice exercises were not in line with their problem spec equivalent, append files were not used in all places for changes, different test cases were used etc. Also some exercises in problem spec changed quite a bit (like grade school) so that only updating the docs would lead to an inconsistent state.

**Comment by IsaacG** [comment]
@junedev I have not gone through them individually, but I can!

Would it make sense to maintain a list of exercises that are (or are not) meant to be in sync with the problem specs? That would all for writing a pretty simple shell script which can be used to sync only the exercises meant to be in sync.

**Comment by IsaacG** [comment]
The following exercises have _some_ degree of diffs. I will revert changes to them. Most of those diffs may be eligible for removal (they don't change the exercises) or just need an append file.

```
 error-handling grade-school grains grep isbn-verifier meetup say wordy
```

**Comment by junedev** [comment]
@IsaacG Thanks a lot for the update. CI did not run for some reason, I will close and re-open the PR, sometimes that helps and I can merge.

**Comment by IsaacG** [comment]
@junedev Thanks! Looks like the checks are all green.

**Review by junedev — APPROVED** [review]
Thanks for the update!

**Comment by Chidinma1709** [comment]
Please i really want to learn but i dont understand anything here

**Comment by IsaacG** [comment]
@Chidinma1709 this PR and GitHub in general is not the appropriate place to ask for help. 

See https://exercism.org/docs/using for docs. If you have questions, please post on the forum: https://forum.exercism.org/

**Pull request merged**
