### PR TITLE
Added go's guidelines in the error concept and in 'the-farm' introduction

### LINKED ISSUE #2011: The Farm: Improve introduction
Follow up from #2009 

The tests for "The Farm" currently don't cover what should happen when a negative fodder amount and a non-scale error is returned. Go's general guideline is to not use the result if there was an error so passing on the error takes precedence over handling the negative amount.

## Tasks
- [x] Add a test case for a negative fodder amount and a non-scale error. The expected outcome of `DevideFood` is 0 and the error that was returned from FodderAmount.
- [ ] Make sure the errors concept and the exercise introduction mention the guideline for usually not using the result in case there was error.

### PR DESCRIPTION
**Pull request by LH-ctrl**
Added a one liner in both documents, but couldn't come up with more detailed information or examples. Hope this will suffice

Resolves #2011

### CODE REVIEW

**Review by junedev — DISMISSED** [review]
It seems you had some mix up with your branches here. The diff ("Files changed") shows the change that was already merged in another PR. I can't see the change you mentioned in the description.

**Comment by LH-ctrl** [comment]
I made a new branch and some more changes to the previous update but whenever i try to push it or make a new pull request, nothing changes. I am at a loss here, sorry.

**Comment by LH-ctrl** [comment]
I managed to get the changes to show up! I deleted the old branch and forked a new one

**Comment by andrerfcsantos** [comment]
@LH-ctrl This branch has conflicts with the main branch. I noticed the branch for this PR is 36 commits behind our main, and in those 36 commits, this exercise was reworked, and that's the main reason why you are seeing conflicts.

Probably the easiest way to fix this is for you to rebase your main branch onto our main branch and fix the conflicts that happen along the way. Then look at the final diff and see if everything still makes sense, keeping in mind that the instructions from the exercise also changed in the repository, compared to the version this branch has.

Alternatively, what you can do is to create a new branch that is up-to-date with our main, do your changes there and then hard reset your main branch (the branch of this PR) to that new branch and force-push the changes to the main branch, which will also update this PR.

**Pull request closed without merging**
