### PR TITLE
randomness: Update introduction on randomness

### PR DESCRIPTION
**Pull request by pawlik**
The seeding behavior changed in version 1.20, and some information was outdated.

I've split the section on Seeding in two: "Prior to 1.20" and "1.20 and later". But I'm open for suggestions if there's a better way to address it.

### CODE REVIEW

**Comment by junedev** [comment]
A maintainer should apply some word smithing before merging this but I will re-open the PR as it is an important thing to address as we support Go 1.20 code on Exercism. Thanks for pointing this out!

**Comment by andrerfcsantos** [comment]
Since `rand.Seed` is being deprecated, we should probably address the recommendation to use it altogether and encourage the use of custom sources vi the exercise itself.

I've put this into my todo list and will take a look at it later.

**Comment by pawlik** [comment]
Thanks for re-opening :) Is there anything I could help with? I could try the "wordsmithing" part but I need more direct feedback. If you want to take it from here, it's also fine.

**Comment by junedev** [comment]
There was a lot more to fix here than just that one file. I decided to make another PR to adjust all the necessary files: https://github.com/exercism/go/pull/2688
I will close this one and merge the other one soon.

**Pull request closed without merging**
