### PR TITLE
[nextercism] Remove all exercise test versioning

### PR DESCRIPTION
**Pull request by alebaffa**
This PR is to solve the issue #857 . It removes all the test versioning from all the tests, stubs and examples. I also removed the related comments (when present) and mentions from `README `and `doc/TESTS.md` .
😃

### CODE REVIEW

**Comment by robphoenix** [comment]
This is fantastic @alebaffa! Thankyou :tada: 

It looks like you might need to rebase this PR against the nextercism branch, rather than fixing the conflicts in a separate commit, you've picked up a commit from master (https://github.com/exercism/go/pull/859/commits/a1d118203ef594df2812f1b49d52dc832b7be42a) and have conflicts in the `bob` exercise that stem from a commit in the nextercism branch (https://github.com/exercism/go/commit/405cd764890a74b61d1e065c5a572f3857b2e6d2). This could well be my fault, sorry, let me know if there's any problems with this.

I'm not going to merge this until I've had the nod from @kytrinyx that this is good to go for Exercism v2. She's currently [taking a well deserved break](https://github.com/exercism/discussions/issues/195) so it may be a short while before this is merged, just so you know why.

**Comment by alebaffa** [comment]
Ok, I will rebase on nextercism. Sorry, I saw your comment while I was doing the second update.

**Comment by robphoenix** [comment]
No worries.

> I also removed the related comments (when present) and mentions from READMEand doc/TESTS.md

:+1:  :+1:  :+1: 
I totally overlooked this in the original issue! :roll_eyes:

**Comment by alebaffa** [comment]
Wow, I don't know how I ended up having 9 commits on this. I will squash them all in one.
I had some issues with go fmt, for some reasons and I think it's mainly due to my VS Code. I discovered too late the awesome `bin/test-without-stubs fmt`.

**Comment by robphoenix** [comment]
> Wow, I don't know how I ended up having 9 commits on this.

:rofl:  I still regularly look at Git and wonder *how on earth did that happen?*

> I will squash them all in one.

Great, be careful not to include the [travis: upgrade Go version](https://github.com/exercism/go/pull/859/commits/74e236c609e06f603a8c67bc40e5b3bd7490cb3f) commit from master branch. Thanks for your patience with the non-simple git shenanigans, this should all be a little easier once Exercism v2 is released and we're just working off Master again.

**Comment by alebaffa** [comment]
Ok, so the situation with the commits is so complicated that it's way easier for me to just restart from scratch (based on nextercism, this time). Please, kindly reject this PR and I will do another one.
Sorry!

**Comment by tleen** [comment]
NP, it happens, you just got caught up in the rather sweeping change between Exercism 1->2.

**Comment by robphoenix** [comment]
No need to apologise @alebaffa!

**Comment by tleen** [comment]
I'm starting to think we may need to make some sort of pull request template that mentions the `nextercism` branch. #862 is going to experience the same issue.

**Comment by robphoenix** [comment]
> I'm starting to think we may need to make some sort of pull request template that mentions the nextercism branch

Yeah, this is a good idea @tleen 
Do you want to open an issue/PR for this? I could get to it later today if you're busy?

**Comment by tleen** [comment]
Opened. I've been a little swamped lately. May not be able to get to it right away, feel free to run with it :smile:.

**Comment by robphoenix** [comment]
:running_man: with it #864 :smile:

**Pull request closed without merging**
