### PR TITLE
anagram: Add test generator

### PR DESCRIPTION
**Pull request by shaleh**
For #605

I did not have a way to wake up #695 so I started a new one.

This generator mimics the output of the connect generator so the output is
a little nicer IMHO. I bumped the `testVersion`.

### CODE REVIEW

**Comment by shaleh** [comment]
Did I break a check? The logs are pretty empty.

**Comment by robphoenix** [comment]
thanks @shaleh I'll have to have a proper look at this on Monday.

> Did I break a check? The logs are pretty empty.

It looks like Travis is complaining about the `testVersion`. We've just removed all test versioning in the `nextercism` branch.

```
# github.com/exercism/go/exercises/anagram
exercises/anagram/anagram_test.go:22: undefined: testVersion
exercises/anagram/anagram_test.go:23: undefined: testVersion
```

**Comment by shaleh** [comment]
Ah. I see. That is disappointing.

**Comment by shaleh** [comment]
All better @robphoenix, thx

**Comment by tleen** [comment]
backlogged will review ASAP.

**Comment by tleen** [comment]
Found #847 while verifying this one. Looks ok in and of itself but this specific exercise does make the bug show up as it has a [multiline most recent remote commit](https://github.com/exercism/problem-specifications/commit/196fc1a2e8274ee082c35442ea4e8b9c8872d9c1) on its canonical-data.json file.

**Comment by tleen** [comment]
I don't see how this passes travis if #847 is a real bug. I'm gonna mess with the build a bit before committing this.

**Comment by tleen** [comment]
Oh I see why, I don't think Travis runs the generators!

**Pull request merged**
