### PR TITLE
[nextercism] remove all exercise test versioning

### PR DESCRIPTION
**Pull request by alebaffa**
This PR is to solve the issue #857 . It removes all the test versioning from all the tests, stubs and examples. I also removed the related comments (when present) and mentions from READMEand doc/TESTS.md .

(This PR is the second attempt after the unsuccessful #859 😋)

### CODE REVIEW

**Comment by alebaffa** [comment]
Thank you, @tleen. I have fixed it (the commits are already squashed). I think it was due to line-ending.

**Comment by tleen** [comment]
I think this looks good but we should wait to merge for [another confirm](https://github.com/exercism/go/pull/859#issuecomment-328867428) that test versioning is a thing of the past.

**Comment by alebaffa** [comment]
@tleen Done. Commit message updated.

**Comment by robphoenix** [comment]
Thanks @alebaffa! This is a significant update :tada:

**Pull request merged**
