### PR TITLE
armstrong-numbers: add exercise with generator (#969)

### PR DESCRIPTION
**Pull request by ilmanzo**
implemented exercise about 'armstrong numbers' in go . Fixes issue #969

### CODE REVIEW

**Comment by ilmanzo** [comment]
I left behind config.json because it's not very clear to me what to put inside... Seems it needs some sort of uuid?

**Comment by ferhatelmas** [comment]
I generated one for you: `b3f06c57-c0de-4b8f-bd16-782b2ce3f478`

For rest of it, please try to copy from other exercise and we can comment on diff if it makes sense.

**Comment by ilmanzo** [comment]
hi, I committed a config.json ... Maybe I missed some documentation on how to generate the UUID and the meaning of the fields ?

**Comment by ferhatelmas** [comment]
@ilmanzo your changes regarding config seem good to me. 

It seems we're missing some documentation on how to update config upon adding new exercise in this track readme. That's why I guess, it's normal if you're confused a bit. We will [try to fix it](#985).

**Comment by ilmanzo** [comment]
Great, thanks! I'm an happy user of exercism and hope to give more contributions in the future!

**Pull request merged**
