### PR TITLE
Simplify linting

### PR DESCRIPTION
**Pull request by ferhatelmas**
Always lint before test and leverage golangci-lint to run

### CODE REVIEW

**Comment by ferhatelmas** [comment]
@leenipper kind reminder to take this in.

**Comment by ferhatelmas** [comment]
@leenipper merging this but feel free to add your suggestions, I can address in a follow up.

**Comment by leenipper** [comment]
It's good.

Sorry to have been disconnected.  We have had 2 deaths in family and unusual travel recently.

**Comment by ferhatelmas** [comment]
Ah, sorry to hear. I wish you the strength to bear.

Thank you for the review in this difficult time.

**Pull request merged**
