### PR TITLE
update code block for direct execution

### PR DESCRIPTION
**Pull request by saurabhmshr**
Updated code block with main function so that code executes locally

### CODE REVIEW

**Review by junedev — COMMENTED** [review]
You raised a valid issue here. However, adding the main package and main function makes it harder to identify the code that the concept is actually about. Imagine all examples would include this. That would be a lot of extra boilerplate code to read for people.

As an alternative, I would suggest you split the code example into two separate code blocks. One shows the definition part. Then you have a sentence that says something like "Now the method can be called on the struct." and then the second part (line 26 and 27). WDYT?

**Review by SR8H — COMMENTED** [review]
split single code block into two

**Comment by SR8H** [comment]
Additionally, I've include the package name in the first code block because the line on top of it says:

> You can only define a method with a receiver whose type is defined in the same package as the method.

**Review by SR8H — COMMENTED** [review]
removed newline before output

**Review by junedev — APPROVED** [review]

**Pull request merged**
