### PR TITLE
markdown: adopt code to pass newly generated tests

### PR DESCRIPTION
**Pull request by Jasstkn**
Signed-off-by: Jasstkn <mariia.kotliarevskaia@gmail.com>

- [x] fix tests for `markdown.go` (students should refactor this code so it should be as bad as possible)
- [x] copied `markdown.go` to examplar.go to pass CI tests

### CODE REVIEW

**Comment by Jasstkn** [comment]
@andrerfcsantos Hello. Could you help me with tests in CI? locally everything pass:
```bash
go test . 
ok      markdown        0.183s
```

**Comment by eklatzer** [comment]
Hey, I have also found a solution passing the tests (#2341), maybe we can work together providing the stub `markdown.go` that has to be refactored.

**Comment by Jasstkn** [comment]
> Hey, I have also found a solution passing the tests (#2341), maybe we can work together providing the stub `markdown.go` that has to be refactored.
> 
> In CI the solution in `example.go` is used and it should show that the problem is solvable (does not matter how clean). The `markdown.go` is only the file that is the starting point for the student. In this case the starting point is a existing code that passes all tests and that should be refactored.

Yes, I understand the difference between those 2 files. I think the examplar solution should somehow implement the language's idiomatic principles that's why I didn't want to just copy Python's code approach. 

Also I checked your `markdown.go` and code there seems to be too good. I think this exercise should contain only one function and be badly written.

**Comment by eklatzer** [comment]
What about using your `markdown.go` and my `example.go`?

**Comment by Jasstkn** [comment]
> What about using your `markdown.go` and my `example.go`?

Yep, good idea. Do you want to push it to my branch? So you input represented as well or otherwise?

**Comment by eklatzer** [comment]
It would be nice if you could fix your CI, so your PR can be merged (I think you only need to copy the content of `markdown.go` to `example.go`). After your PR is merged, mine can be merged

**Comment by Jasstkn** [comment]
> It would be nice if you could fix your CI, so your PR can be merged (I think you only need to copy the content of `markdown.go` to `example.go`). After your PR is merged, mine can be merged

Okay, I'll copy your example.go then.

**Comment by eklatzer** [comment]
Why did you copy my version? My version will be merged here: #2341

**Comment by Jasstkn** [comment]
@eklatzer done. 
@andrerfcsantos Could you review what we have here?

**Comment by Jasstkn** [comment]
> Why did you copy my version? My version will be merged here: #2341

My bad. I misunderstood what you mean.

**Comment by eklatzer** [comment]
Thanks, why did you delete `gen.go`?

**Comment by Jasstkn** [comment]
> Thanks, why did you delete `gen.go`?

I guess it caused some issues for me to test it locally. Restored.

I don't know if I should fix linter's errors regarding style. What do you think?

**Comment by eklatzer** [comment]
> I don't know if I should fix linter's errors regarding style. What do you think?

I think only changes passing CI are merged, so I think you have to

**Comment by Jasstkn** [comment]
> > I don't know if I should fix linter's errors regarding style. What do you think?
> 
> I think only changes passing CI are merged, so I think you have to

it's green now ✅

**Comment by eklatzer** [comment]
Thanks

**Review by andrerfcsantos — APPROVED** [review]
Thanks for this and sorry for the delay reviewing it.

Extra kudos for the awesome collaboration going on here, you rock :)

**Pull request merged**
