### PR TITLE
Remove obsolete concept

### PR DESCRIPTION
**Pull request by junedev**
This removes an unused concept. (We have more unused concepts to clean up later, this is a first test.)

@ErikSchierboom Jeremy thinks just removing the concept like this will be fine but he would like you to try it out locally once you are back to make sure it works. (see https://exercism-team.slack.com/archives/GC3K95MRR/p1639397789176100)

### CODE REVIEW

**Comment by jmrunkle** [comment]
This looks fine, is there any reason it is still just a draft?

**Comment by jmrunkle** [comment]
> This looks fine, is there any reason it is still just a draft?

Just read your first comment - I gather you are waiting for Erik to take a look before we mark it as "ready for review"

**Comment by junedev** [comment]
@jmrunkle Yes, exactly.

**Review by ErikSchierboom — APPROVED** [review]
Just tested this locally and it works fine.

**Comment by junedev** [comment]
Great, thanks!

**Pull request merged**
