### PR TITLE
Add missing parameters to stub

### LINKED ISSUE #1527: Gross Store wrong arguments number or wrong signature of AddItem and RemoveItem functions
In "Gross Store" exercise the function `AddItem` has the following signature:

```go
func AddItem(bill map[string]int, item string, unit string) bool {}
```

3 arguments.

In test file it is called:

```go
ok := AddItem(bill, units, item.name, item.unit)
```

4 arguments.

The same is for `RemoveItem` function.

What should be changed? The test or the source?

### LINKED ISSUE #1537: gross-store function signatures for AddItem and RemoveItem are missing "units map[string]int" parameter
The tests require the units parameter:

* https://github.com/exercism/go/blob/main/exercises/concept/gross-store/gross_store_test.go#L74
* https://github.com/exercism/go/blob/main/exercises/concept/gross-store/gross_store_test.go#L155

The exemplar has the correct parameters:

* https://github.com/exercism/go/blob/main/exercises/concept/gross-store/.meta/exemplar.go#L21
* https://github.com/exercism/go/blob/main/exercises/concept/gross-store/.meta/exemplar.go#L32

But the stub given to students does not:

* https://github.com/exercism/go/blob/main/exercises/concept/gross-store/gross_store.go#L14
* https://github.com/exercism/go/blob/main/exercises/concept/gross-store/gross_store.go#L19

This is particularly confusing and frustrating for students using the browser editor because they cannot see the tests to know why they are failing to compile correctly.

### PR DESCRIPTION
**Pull request by jmrunkle**
Fixes #1527

### CODE REVIEW

**Comment by geoffreywiseman** [comment]
If exercism were to use this path, the instructions should also be updated, since they show invocations without the units.

I still prefer the other path, mostly for aesthetic reasons, but I recognize that either is a valid fix.

**Comment by jmrunkle** [comment]
> If exercism were to use this path, the instructions should also be updated, since they show invocations without the units.

Updated the instructions which were pretty bad / not explicit enough even if we used only 3 params.

**Comment by jmrunkle** [comment]
Apparently gocritic complains if you do not combine the two parameters with the same type:

```
exercises/concept/gross-store/gross_store.go:14:1: paramTypeCombine: func(bill map[string]int, units map[string]int, item string, unit string) bool could be replaced with func(bill, units map[string]int, item, unit string) bool (gocritic)
func AddItem(bill map[string]int, units map[string]int, item string, unit string) bool {
^
exercises/concept/gross-store/gross_store.go:19:1: paramTypeCombine: func(bill map[string]int, units map[string]int, item string, unit string) bool could be replaced with func(bill, units map[string]int, item, unit string) bool (gocritic)
func RemoveItem(bill map[string]int, units map[string]int, item string, unit string) bool {
```

I'll do that even though I find it less clear personally.

**Comment by jmrunkle** [comment]
NOTE: All other test failures are pre-existing issues. There's actually one more set for gross-store, but I did not change the tests (so also pre-existing):

```
exercises/concept/gross-store/gross_store_test.go:14:2: SA4006: this value of `tests` is never used (staticcheck)
	tests := []struct {
	^
exercises/concept/gross-store/gross_store_test.go:42:2: SA4006: this value of `tests` is never used (staticcheck)
	tests := []struct {
	^
exercises/concept/gross-store/gross_store_test.go:100:2: SA4006: this value of `tests` is never used (staticcheck)
	tests := []struct {
	^
```

They sure look used to me...

**Review by ekingery — APPROVED** [review]
I don't fully understand the nuances here and can't commit the time to test thoroughly, but the code looks good. Thanks @jmrunkle!

**Pull request merged**
