### PR TITLE
Error Message update for negative span

### PR DESCRIPTION
**Pull request by deepaksathya**
Updated the error message for negative span.  Submitted for review

### CODE REVIEW

**Comment by iHiD** [comment]
@deepaksathya If you add the text `Closes #1434` into the description of this PR, then when it's merged that issue will automatically get closed too 🙂

**Review by deepaksathya — COMMENTED** [review]
Closes

**Comment by deepaksathya** [comment]
@iHiD Sorry, I think I  didn't get it right with pull request process. If you think it is too much of a trouble, you may go ahead with the changes yourself.

**Review by ekingery — APPROVED** [review]

**Comment by ekingery** [comment]
> @iHiD Sorry, I think I didn't get it right with pull request process. If you think it is too much of a trouble, you may go ahead with the changes yourself.

Thanks for your contribution, @deepaksathya! Don't worry about the closing comment - that is just a convenient way to do two things at once. The PR looks good, it is now merged. As a heads up, this will not be reflected in the existing exercism site, as it is frozen while Exercism V3 is preparing for launch.

**Comment by iHiD** [comment]
@deepaksathya I've edited the original PR description so you can see what I meant for future, but as Eric says, you did good! :)

**Comment by deepaksathya** [comment]
Thanks. Deleted  my branch

**Pull request merged**
