### PR TITLE
flatten-array: add exercise with test generator

### PR DESCRIPTION
**Pull request by ferhatelmas**

### CODE REVIEW

**Comment by ferhatelmas** [comment]
Note that I didn't add it into config since I have no idea regarding order, difficulty, etc. I hope we can tune them while reviewing.

**Comment by tleen** [comment]
Looks good so far but we should get it in config.json so it can pass the configlet lint in Travis. 

If I was going to ballpark difficulty I would say 3. My gut feeling is that it should be unlocked by `error-handling` seems like it would group well with the other unlocks `circular-buffer` and `custom-set`. 

Topics-wise probably: recursion, arrays?

**Comment by ferhatelmas** [comment]
@tleen your suggestions seem good to me. I will add them but I have one question regarding UUID generation. We're supposed to use `configlet` right ?

If so, it currently generates weird ones (one example: `42a9ee65-00c7-9680-2bd3-42155d751e1124c902a`) but issue is related to library and I will create an issue there.

**Comment by ferhatelmas** [comment]
@tleen updated as your suggestions.

However, I really suggest changing `uuid` library in `configlet`. Let me know if I'm missing anything.

**Comment by ferhatelmas** [comment]
Let's merge then.

**Pull request merged**
