### PR TITLE
config.json: add info for bank-account

### PR DESCRIPTION
**Pull request by tleen**
See #345

### CODE REVIEW

**Comment by robphoenix** [comment]
Sorry @tleen, I pressed the `resolve conflicts` button :grimacing:, I've never used that feature before and I couldn't help myself finding out what it did.
You'll probably want to pull my commit down and rebase the changes onto your commit, sorry for the extra work, still learning!! :grinning: 
Also, watch the indentation on the topics, a minor thing perhaps but good to stay consistent :smile:

**Comment by tleen** [comment]
Np, I haven't used that button either.

**Comment by tleen** [comment]
I thought I was going to have to redo this one but the resolve conflicts fixed it. yay!

**Comment by tleen** [comment]
Hm, after rebase I see your changes but not in the file compare. Would merging this as is screw things up?

**Comment by robphoenix** [comment]
I think it would. The changes aren't showing up in the `Files changed` tab and we don't want to include this commit, https://github.com/exercism/go/pull/709/commits/13a1aaf1e2539d50154e6e35de9bb0a6ed37c38c, either.

I'm afraid it might be easier to redo on these changes. Sorry, I should've waited for these to be merged before merging #720

**Comment by tleen** [comment]
NP its an easy redo. :smile:

**Pull request closed without merging**
