### PR TITLE
adding in benchmem to tests

### PR DESCRIPTION
**Pull request by sebito91**

### CODE REVIEW

**Comment by sebito91** [comment]
Mentioned this one in the exercism mentors track, would be nice to add some extra verbosity to user tests when they run the suite.

The example below is trivial, but for other challenges with benchmarks it would be helpful to understand how performant the solution is.

```
[sborza@icebox]:~/.../mentorcism/go/hello-world (master %):$ go test -v --bench .
=== RUN   TestHelloWorld
--- PASS: TestHelloWorld (0.00s)
goos: linux
goarch: amd64
pkg: github.com/sebito91/challenges/mentorcism/go/hello-world
BenchmarkHelloWorld-8           2000000000               0.55 ns/op
PASS
ok      github.com/sebito91/challenges/mentorcism/go/hello-world        1.174s
[sborza@icebox]:~/.../mentorcism/go/hello-world (master %):$ go test -v --bench . --benchmem
=== RUN   TestHelloWorld
--- PASS: TestHelloWorld (0.00s)
goos: linux
goarch: amd64
pkg: github.com/sebito91/challenges/mentorcism/go/hello-world
BenchmarkHelloWorld-8           2000000000               0.55 ns/op            0 B/op          0 allocs/op
PASS
ok      github.com/sebito91/challenges/mentorcism/go/hello-world        1.165s
```

**Comment by sebito91** [comment]
No, I did a massive `sed` across the repo. Should I just update the `config/exercise_readme.go.tmpl`?

**Comment by sebito91** [comment]
No, I did a massive `sed` across the repo. Should I just update the `config/exercise_readme.go.tmpl`?

**Comment by leenipper** [comment]
Yes. I think the .tmpl change should be enough for starters.  Then running configlet generate will take care of the README.md files. We still commit all the REAME.md files just the same after running configlet.
Use ./bin/fetch-configlet to get the up to date configlet.
Then use ./bin/configlet  generate --help.  I think the default is to generate all the README.md files.
Compare resulting README.md to the changes made with sed.  If all changes match, all ok.

**Comment by sebito91** [comment]
OK, on it now!

**Comment by sebito91** [comment]
Tests aren't passing for same reasons as #1124, just FYI.

```
[sborza@icebox]:~/src/github.com/exercism/go (benchmem):$ ./bin/test-without-stubs fmt
moving stub exercises/acronym//acronym.go
moving stub exercises/bob//bob.go
moving stub exercises/gigasecond//gigasecond.go
moving stub exercises/hamming//hamming.go
moving stub exercises/hello-world//hello_world.go
moving stub exercises/leap//leap.go
moving stub exercises/ledger//ledger.go
moving stub exercises/markdown//markdown.go
moving stub exercises/nucleotide-count//nucleotide_count.go
moving stub exercises/proverb//proverb.go
moving stub exercises/rna-transcription//rna_transcription.go
moving stub exercises/tree-building//tree_building.go
moving stub exercises/triangle//triangle.go
moving stub exercises/two-fer//two_fer.go
moving stub files back
```

**Comment by leenipper** [comment]
With #1125 I corrected the travis-cii problem.  I think this PR will need a rebase to upstream/master and then a push --force. The PR might auto close and then need re-opening; try it and see. Thanks.

**Pull request merged**
