### PR TITLE
maintainers: add my bio as an alumnus

### PR DESCRIPTION
**Pull request by petertseng**
As noted in https://github.com/exercism/go/issues/719 I cannot currently
fulfill my duties as a maintainer of this track, so it is right and
proper to mark myself as an alumnus as a result.

I will do as Katrina did in https://github.com/exercism/go/pull/797 and
submit a bio for myself. I think this is suitable for showing on the
website (by the way, Katrina's currently isn't being shown).

### CODE REVIEW

**Comment by tleen** [comment]
WIth reluctance, approving. Glad to have you pushing Nextersicm, sad to miss you day-to-day.

**Comment by petertseng** [comment]
> Glad to have you pushing Nextersicm

I can't accept credit for doing that. I'm just reacting to all the PRs in all other tracks, not initiating any actions of my own.

**Comment by petertseng** [comment]
> by the way, Katrina's currently isn't

Oh no, I meant Katrina's isn't being **shown**, not that it isn't **suitable**, I am sorry. Editing my commit message (commit contents are not changing).

**Comment by tleen** [comment]
> I can't accept credit for doing that. I'm just reacting to all the PRs in all other tracks, not initiating any actions of my own.

Me too, but that's how large scale updates get done. Everyone doing their part....

**Comment by tleen** [comment]
@kytrinyx added her own bio so if she would like to update who wouldn't want to be in that company? :smile:

**Comment by kytrinyx** [comment]
I've made a note that we need to show alumni maintainers (and mark them as such in the UI).

**Comment by robphoenix** [comment]
Yep, sad to have this merged, but so so grateful to your presence and guidance here and the opportunity provided by your invitation to join you in maintaining this track.
I raise a glass to you @petertseng :heart:

**Comment by kytrinyx** [comment]
Thank you so much, @petertseng, for all the work that you've done to take the Go track to another level. It's ever so much better for having had the benefit of your attention for a couple of years!

**Pull request merged**
