### PR TITLE
Issue 2475 roman numerals max 3999

### PR DESCRIPTION
**Pull request by dbh**
Adjust Instructions and Unit Tests to support maximum Roman numeral 3999
Resolves https://github.com/exercism/go/issues/2475

Adjustment to problem specification, instructions, and unit tests to support the max val 3,999 which can be expressed in Roman numerals (without getting into the "Larger number" scenarios)

### CODE REVIEW

**Comment by dbh** [comment]
@junedev @IsaacG  Would you kindly review? This is the Go-Lang exercise follow up for the recently approved Problem Spec clarification for Roman numerals. I ran configlet to sync the problem spec instructions and test cases into the toml

Thanks!

Go-Lang 
issue https://github.com/exercism/go/issues/2475

Problem Spec (merged/closed)
PR https://github.com/exercism/problem-specifications/pull/2094
Issue https://github.com/exercism/problem-specifications/issues/2095

**Review by IsaacG — APPROVED** [review]
Looks good to me but I'd defer for a track maintainer, which I'm not :)

**Comment by dbh** [comment]
@junedev Thanks for pointing out the necessary changes in the example solution in .meta folder

**Review by junedev — APPROVED** [review]
FYI for next time: For updating the cases_test.go file, we have a generator for this exercise. How to run it is described in step 2 here: https://github.com/exercism/go#synchronizing-tests-and-instructions.
I ran it for you so the comment at the top also contains the correct commit now.

**Pull request merged**
