### PR TITLE
[WIP] Restructure exercises

### LINKED ISSUE #794: Choose core exercises structure
From #717:

If you haven't already, now would be a good time to do the following:

~~- [x] add a rough estimate of difficulty to each exercise (scale: 1-10)~~
~~- [x] add topics to each exercise~~
- [ ] choose *at most 20 exercises* to be core exercises (set `core: true`, and delete the `unlocked_by` key)
- [ ] for each exercise that is not core, decide which exercise is the prerequisite (max 1)

If possible, leave 3 or 4 simple exercises as (core: false, unlocked_by: null), as this will provide new participants with some exercises that they can tackle even if they have not finished the first core exercise.

### PR DESCRIPTION
**Pull request by robphoenix**
Closes #794

### CODE REVIEW

**Comment by robphoenix** [comment]
config-viz

**Comment by robphoenix** [comment]
I had only intended to outline core exercises, but got carried away. This is very much a WIP, and expect exercises to move around, as well as maybe changes in topics/difficulty. I think if we can agree on our core topics first then that would be great.

**Comment by tleen** [comment]
[kindergarten-garden](https://github.com/exercism/go/tree/master/exercises/kindergarten-garden) may be a good for unlocking [tournament](https://github.com/exercism/go/tree/master/exercises/tournament). They are very similar (treat a formatted string as a recordset and do stuff with the data), the latter perhaps a little more difficult.

**Comment by robphoenix** [comment]
@tleen yep, good idea. 

Shall I merge this in, to update as necessary over time, or do you think we need more discussion before merging?

**Comment by tleen** [comment]
I would say merge it in as-is, and we can do individual discussions/commits to it as refinements. This way we are compatible with nextercism now and our changes can be small and focused. There are definitely things I will suggest to change over time (ex: IMO [error-handling](https://github.com/exercism/go/tree/master/exercises/error-handling) should probably be earlier and core), but nothing that should block this from being the track config for now.

**Comment by robphoenix** [comment]
@tleen Yeah, I agree error-handling should be earlier in the track, though I think it needs some reworking before that. I think we may find that this provides good opportunity to improve some exercises, their README's, their difficulty rating and topics list.

I've been quite behind with this repo, and have a few things in my TODO list, with this biggie merged I hope to start chipping away at the smaller stuff.

**Pull request merged**
