### PR TITLE
Fixed "Output" - Welcome To The Tech Palace (Fixes #2156)

### LINKED ISSUE #2156: Code examples: "Output" for non print statements can be confusing
Hi, I started to use Exercism for practice in Golang recently and I like you product. Thank you for you job 👍🏼 
I have one remark.

I've noticed that https://exercism.org/tracks/go/exercises/annalyns-infiltration has nice code example with Output after fmt.Println:
```var knightIsAwake = false
var archerIsAwake = true
var prisonerIsAwake = false
var petDogIsPresent = false
fmt.Println(CanFreePrisoner(knightIsAwake, archerIsAwake, prisonerIsAwake, petDogIsPresent))
// Output: false
```

but if you take a look at this example https://exercism.org/tracks/go/exercises/vehicle-purchase (and most of other)

```
needLicense := NeedsLicense("car")
// Output: true
```

it also has **Output** but there is no function to Print variable `needLicense`. It can be confusing.
I would recommend to use one style in each task: use `fmt.Println()` before `// Output:` or show value of variable in other way.

### PR DESCRIPTION
**Pull request by TristanAppDev**
Changed "Output" to "=>" - Welcome To The Tech Palace

Related to #2202

### CODE REVIEW

**Comment by TristanAppDev** [comment]
This one looks kind of strange to me with the "=>".
```
AddBorder("Welcome!", 10)
// =>
// **********
// Welcome!
// **********
```

**Review by andrerfcsantos — CHANGES_REQUESTED** [review]
Thanks for fixing this in this exercise too.

The changes you made are correct. However, this exercise also has code examples in the [introduction](https://github.com/exercism/go/blob/main/exercises/concept/welcome-to-tech-palace/.docs/introduction.md). The content in that introduction in turn is also present in the [introduction.md](https://github.com/exercism/go/blob/main/concepts/strings/introduction.md) and [about.md](https://github.com/exercism/go/blob/main/concepts/strings/about.md) of the `strings` concept.

If it is not much to ask, can you fix the code examples in those files too?

**Comment by TristanAppDev** [comment]
Sure, I'll have a look.

**Comment by TristanAppDev** [comment]
I'm still interested. Just have been too busy last weeks.
Sorry for letting you wait.

**Comment by andrerfcsantos** [comment]
@TristanAppDev No problem, thanks for letting us know.

Finish when you have the time and if you lose interest that's ok too, just let us know.

**Review by andrerfcsantos — APPROVED** [review]
There has been some interest from other contributors to fix this issue across the track. Since I had some free time and to make sure this PR is not superseded by another or having someone doing duplicate work, I took the time to finish it so we can merge it!

Thanks again for this contribution.

**Pull request merged**
