### PR TITLE
acronym: fix for apostrophe

### PR DESCRIPTION
**Pull request by ilmanzo**
fix issue #1189

### CODE REVIEW

**Comment by kytrinyx** [comment]
Apologies for the long silence, @ilmanzo, it looks like all the maintainers of this track got caught up in life outside of open source.

The build is failing, but not because of you 🍰 -- would you mind rebasing against the most recent master and push this back up to see if it goes green?

**Comment by kytrinyx** [comment]
Thanks @ilmanzo, I rebased this for you, and will merge it once the build finishes.

**Comment by kytrinyx** [comment]
BTW @ilmanzo In the future, if you say "fixes #1189" instead of "fix issue #1189", then the original issue will be closed automatically when the PR gets merged. You can read more about this (and other ways of doing the same thing) in https://blog.github.com/2013-05-14-closing-issues-via-pull-requests/

**Comment by ilmanzo** [comment]
> BTW @ilmanzo In the future, if you say "fixes #1189" instead of "fix issue #1189", then the original issue will be closed automatically when the PR gets merged. You can read more about this (and other ways of doing the same thing) in https://blog.github.com/2013-05-14-closing-issues-via-pull-requests/

thanks for the hint, I forgot that :+1:

**Pull request merged**
