### PR TITLE
Add tasks to `the-farm` introduction

### LINKED ISSUE #1639: the-farm: add tasks to introduction
The [instructions.md document](https://github.com/exercism/go/blob/main/exercises/concept/the-farm/.docs/instructions.md) of the `the-farm` exercise does not conform to the standard. The first part is fine, but the second part should be formatted differently and have one or more tasks. See [these instructions](https://github.com/exercism/go/blob/main/exercises/concept/lasagna/.docs/instructions.md) for an example.

### PR DESCRIPTION
**Pull request by jmrunkle**
Also
- changed the tasks slightly to not only use a specific error, but also to return a specific error.
- change the test structure so that it uses the current style of table-driven tests

Fixes #1639

### CODE REVIEW

**Comment by bitfield** [comment]
One suggestion: instead of using sentinel errors (`ErrWeight`, `SillyNephew`), what do you think about using custom error types instead? The advantage of this would be that you can convey information about the invalid input within the error:

```go
return SillyNephew{fmt.Errorf("negative cows: %d", cows)}
```

The type of the error can be checked at the other end with `errors.As` (instead of `errors.Is` for sentinel errors).

**Comment by jmrunkle** [comment]
> One suggestion: instead of using sentinel errors (`ErrWeight`, `SillyNephew`), what do you think about using custom error types instead? The advantage of this would be that you can convey information about the invalid input within the error:
> 
> ```go
> return SillyNephew{fmt.Errorf("negative cows: %d", cows)}
> ```
> 
> The type of the error can be checked at the other end with `errors.As` (instead of `errors.Is` for sentinel errors).

I like the idea, and there is another issue for teaching about interfaces in this exercise. I could just take care of both in this PR, but I was planning to do it separately since adding the `interfaces` concept will also involve adding a bunch of documentation / metadata for the new concept. Mind if I punt on that @bitfield?

**Comment by bitfield** [comment]
Absolutely. Keep up the fine work!

**Comment by junedev** [comment]
regarding the error wrapping (not relevant for this specific PR): I think it is important to also know how not to unwrap, so I would use this exercise to show the old equal and type assertion way of error checking and then use the "deep thought" exercise later to explain error wrapping and errors.Is and errors.As. Just a thought, feel free to ignore.

**Review by junedev — APPROVED** [review]

**Pull request merged**
