### PR TITLE
added test case for negative amount with non-scale error #2011

### PR DESCRIPTION
**Pull request by est5**
Part of #2011

### CODE REVIEW

**Review by andrerfcsantos — APPROVED** [review]
Thanks for this!

**Comment by enarha** [comment]
Hi, as I understand it, this test contradicts to the exercise instructions. The instructions say "If the scale is broken and returning negative amounts of fodder, return an error saying "negative fodder". This test checks for negative value, but expects "non-scale error"

**Comment by junedev** [comment]
@enarha It might seem a bit strange but it is all correct. The test in this PR tests that the solution checks the error first and only evaluates the actual result of the function of the error is either `nil` or is the special `ErrScaleMalfunction`. See https://github.com/exercism/go/issues/2011#issuecomment-1001638982 for details.

**Comment by junedev** [comment]
@enarha There was a task to update the concept introduction accordingly but I think there was some issue with merging that change. I will re-open the respective issue and we will make sure the documentation on this will be improved.

**Pull request merged**
