### PR TITLE
lasagna: Reorder instructions

### PR DESCRIPTION
**Pull request by SaschaMann**
The first task requires defining a constant, not a function, so this matches that order.

### CODE REVIEW

**Review by junedev — COMMENTED** [review]
I think generally it makes more sense to introduce variables before functions. Could you apply the same change to the concept docs (introduction and about)?

**Comment by junedev** [comment]
@bobtfish Is it ok to merge this or will that mess with the lasagna branch you are working on and you rather want to make the changes yourself there?

**Comment by SaschaMann** [comment]
> Could you apply the same change to the concept docs (introduction and about)?

Sure, I'll wait for @bobtfish's response first

**Comment by bobtfish** [comment]
I don’t mind! Please feel free to fix everywhere @SaschaMann and we can merge this, or I’m happy to take care of it in my branch 🙃

**Comment by junedev** [comment]
@bobtfish Then I decide you will take care of this of this in your PR. I will leave a note in the draft PR.

**Pull request closed without merging**
