### PR TITLE
pangram: clarify language in README

### LINKED ISSUE #801: Pangram README claims input will only have ASCII
The README says:

    The alphabet used consists of ASCII letters `a` to `z`, inclusive, and is case
    insensitive. Input will not contain non-ASCII symbols.

There are German characters in one test which causes failures if not ignored or counted. But even then tests fail if code does not handle characters outside of ASCII. Specifically, Russian.

    --- FAIL: TestPangram (0.00s)
	pangram_test.go:37: Pangram test [Широкая электрификация южных губерний даст мощный толчок подъёму сельского хозяйства.], expected [false], actual [true]
	pangram_test.go:39: [Широкая электрификация южных губерний даст мощный толчок подъёму сельского хозяйства.] should not be a pangram because : Panagram in alphabet other than ASCII

I am OK with having to check if a rune is ASCII or not. But the README explicitly says not to worry about it. Or is 'symbols' here meant to mean things other than letters like braces, emoji, and the like? Either way the README is at best not clear and at worst wrong.

### PR DESCRIPTION
**Pull request by tleen**
Made README clearer in regards to allowed inputs for pangram / allowed
inputs for interface.

Added the term 'rune' into the problem context.

Resolves #801

### CODE REVIEW

**Comment by robphoenix** [comment]
I'm not fully up on generating the READMEs, is this in danger of being overwritten?

**Comment by tleen** [comment]
I don't think so, I believe that was a one time thing? I do have to look into it more, it's part of the reason why #786 has been sitting around. If that ends up happening we can redo in the local metafile or wherever.

**Comment by tleen** [comment]
Yes, it would be overwritten but by us via configlet, automation in README's is a thing of the past. See the comment in 4a9e2a05b1a5e4ee9b9c31bea2fe3128b8935bcb.

**Comment by robphoenix** [comment]
Okay, yeah, unless we change the description.md in the `problem-specifications` repo, then anything we add to `hints.md` will be additional. To change this we need to re-write it here. I suppose we just need to be considerate of this if we ever want to regenerate READMEs in the future and not just do them all.

**Comment by tleen** [comment]
This may be a good example of why we moved to locally generated READMEs in the first place.

**Comment by robphoenix** [comment]
I wonder if we're addressing the wrong problem here. Looking at https://github.com/exercism/problem-specifications/commit/ff2abe7ed8ba8021f6b1b22f57703dd4225ff6a4 & https://github.com/exercism/problem-specifications/issues/842 it may be that we should update the test suite to reflect the `canonical-data.json` instead of rewriting the README. And then add a generator when we can.

**Comment by tleen** [comment]
Yeah, I think that is better since we are the divergent track here.

**Comment by robphoenix** [comment]
Okay, do you want to update the `config.json` manually now until we implement the generator?

**Comment by tleen** [comment]
I was gonna yank those two entries out of the test suite?

**Comment by robphoenix** [comment]
Sounds good :+1:

**Pull request closed without merging**
