### PR TITLE
Add instructions to create errors

### PR DESCRIPTION
**Pull request by scubbo**
At this point in the syllabus, error-creation has not yet been
introduced!

### CODE REVIEW

**Comment by scubbo** [comment]
image

See image screenshotted from [here](https://exercism.org/tracks/go/concepts). Alternatively, the `errors` exercise could be made a prerequisite of the `First class functions` exercise, but I don't know how to go about that.

**Comment by junedev** [comment]
@scubbo I think your second idea (adding errors to the prequesites) is the better course of action here. It does not hurt that this concept/exercise moved further down in the tree.

Would be great if you could adjust the PR accordingly.

**Comment by scubbo** [comment]
I believe I've updated the track such that the "First-class functions" exercise is dependent upon "Errors". However, I should stress that this is my first time contributing to an Exercism track - although I have read through [this page](https://github.com/exercism/go), I don't know how to confirm that this change is correct (in particular, I don't know how I'd detect a circular dependency).

**Review by junedev — APPROVED** [review]
Looks all correct. We have a tool in the CI pipeline that would throw an error if there would be an issue with building up the concept tree. Since your PR passes all the checks, you can rest assured its all good. 🙂

**Comment by scubbo** [comment]
Sweet - it's great to be working in a project with robust CI/CD practices! Thanks for your help :)

**Pull request merged**
