### PR TITLE
updating travis to add golanci-lint check

### PR DESCRIPTION
**Pull request by sebito91**
Per the discussion in https://github.com/exercism/go/issues/1024 we decided we wanted to include additional linting as part of the build. Originally we discussed adding gometalinter, but then golangci-lint came along, which is an improvement.

Closes https://github.com/exercism/go/issues/1024

### CODE REVIEW

**Comment by bitfield** [comment]
@sebito91: happy to work with you on this one to get all the exercises passing `golangci-lint` if you like.

**Comment by sebito91** [comment]
Sounds good @bitfield, I totally biffed on this one and kind of left it for a while. I'll give it another go this weekend and ping you on slack.

**Comment by leenipper** [comment]
I've been working up a series of exercise commits to make the golangci-lint pass.  Should I submit a PR with them?  I didn't want to jump ahead for work you already have ongoing @sebito91, but I am glad to help out on it.  I've been covered up for a while and just now stepping back into "the role" again.

**Comment by sebito91** [comment]
Please go ahead @leenipper, been consumed with work things at the moment! Will close this PR out.

**Pull request closed without merging**
